spring.application.name=E-Commerce Product API
server.port=8080
server.servlet.context-path=/

# PostgreSQL Database Configuration
# Change these values according to your PostgreSQL setup
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Test@123

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (disabled for PostgreSQL - enable only if using H2)
spring.h2.console.enabled=false
